# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: `MIT

full:
  electricity:
    conventional_carriers: []
    renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]
    extendable_carriers:
      Generator: [solar, onwind, offwind-ac, offwind-dc] # omit hydro
      StorageUnit: [battery] # a storage unit with inherent power conversion; e_nom and p_nom connected via e_nom = p_nom * max_hours so extending requires high investment in both
      Store: [H2] # storage without inherent power conversion; sets e_nom
      Link: [H2 pipeline] # sets p_nom
    transmission_limit: vopt
